/**
 * Revenue Settlement and Sharing System GE
 * Copyright (C) 2011-2014,  Javier Lucio - lucio@tid.es
 * Telefonica Investigacion y Desarrollo, S.A.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

package es.tid.fiware.rss.model;

// Generated 10-feb-2012 11:04:29 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * BmPbMopId generated by hbm2java.
 */
@Embeddable
public class BmPbMopId implements java.io.Serializable {

    private long bmPbId;
    private long nuMopId;

    /**
     * Constructor.
     */
    public BmPbMopId() {
    }

    /**
     * Constructor.
     * 
     * @param bmPbId
     * @param nuMopId
     */
    public BmPbMopId(long bmPbId, long nuMopId) {
        this.bmPbId = bmPbId;
        this.nuMopId = nuMopId;
    }

    @Column(name = "BM_PB_ID", nullable = false, precision = 10, scale = 0)
    public long getBmPbId() {
        return this.bmPbId;
    }

    public void setBmPbId(long bmPbId) {
        this.bmPbId = bmPbId;
    }

    @Column(name = "NU_MOP_ID", nullable = false, precision = 10, scale = 0)
    public long getNuMopId() {
        return this.nuMopId;
    }

    public void setNuMopId(long nuMopId) {
        this.nuMopId = nuMopId;
    }

    /**
     * Overriden.
     * 
     * @param other
     * @return
     */
    @Override
    public boolean equals(Object other) {
        if (this == other) {
            return true;
        }
        if (other == null) {
            return false;
        }
        if (!(other instanceof BmPbMopId)) {
            return false;
        }
        BmPbMopId castOther = (BmPbMopId) other;

        return (this.getBmPbId() == castOther.getBmPbId())
            && (this.getNuMopId() == castOther.getNuMopId());
    }

    /**
     * Overriden.
     * 
     * @return
     */
    @Override
    public int hashCode() {
        int result = 17;

        result = 37 * result + (int) this.getBmPbId();
        result = 37 * result + (int) this.getNuMopId();
        return result;
    }

}
