#
# STRUCTURE FOR TABLE "BM_CURRENCY" 
#

DROP TABLE IF EXISTS `BM_CURRENCY`;
CREATE TABLE `BM_CURRENCY` (
  `NU_CURRENCY_ID` BIGINT(10) NOT NULL,
  `TX_ISO4217_CODE` VARCHAR(3) CHARACTER SET LATIN1 COLLATE LATIN1_BIN NOT NULL,
  `TX_DESCRIPTION` VARCHAR(20) CHARACTER SET LATIN1 COLLATE LATIN1_BIN DEFAULT NULL,
  `TC_SYMBOL` VARCHAR(5) CHARACTER SET LATIN1 COLLATE LATIN1_BIN NOT NULL,
  `TX_ISO4217_CODE_NUM` VARCHAR(3) CHARACTER SET LATIN1 COLLATE LATIN1_BIN NOT NULL,
  `NU_ISO4217_DECIMALS` INT(3) NOT NULL DEFAULT '0',
  PRIMARY KEY (`NU_CURRENCY_ID`),
  UNIQUE KEY `UQ_BM_CURRENCY_ISO4217` (`TX_ISO4217_CODE`)
) ENGINE=INNODB DEFAULT CHARSET=LATIN1 ROW_FORMAT=COMPACT;

#
# STRUCTURE FOR TABLE "BM_LANGUAGE"
#

DROP TABLE IF EXISTS `BM_LANGUAGE`;
CREATE TABLE `BM_LANGUAGE` (
  `NU_LANGUAGE_ID` BIGINT(10) NOT NULL,
  `TX_NAME` VARCHAR(20) CHARACTER SET LATIN1 COLLATE LATIN1_BIN NOT NULL,
  `TX_ISO639_1_CODE` CHAR(3) CHARACTER SET LATIN1 COLLATE LATIN1_BIN NOT NULL,
  `TX_ISO639_CODE` CHAR(2) CHARACTER SET LATIN1 COLLATE LATIN1_BIN NOT NULL,
  PRIMARY KEY (`NU_LANGUAGE_ID`),
  UNIQUE KEY `UQ_BM_LANGUAGE_ISO639` (`TX_ISO639_1_CODE`),
  UNIQUE KEY `UQ_BM_LANGUAGE_NAME` (`TX_NAME`)
) ENGINE=INNODB DEFAULT CHARSET=LATIN1 ROW_FORMAT=COMPACT;

#
# STRUCTURE FOR TABLE "BM_COUNTRY"
#

DROP TABLE IF EXISTS `BM_COUNTRY`;
CREATE TABLE `BM_COUNTRY` (
  `NU_COUNTRY_ID` BIGINT(10) NOT NULL,
  `TX_ITU_T212_CODE` VARCHAR(20) CHARACTER SET LATIN1 COLLATE LATIN1_BIN NOT NULL,
  `TX_ISO3166_CODE` CHAR(2) CHARACTER SET LATIN1 COLLATE LATIN1_BIN NOT NULL,
  `NU_CURRENCY_ID` BIGINT(10) NOT NULL,
  `NU_LANGUAGE_ID` BIGINT(10) NOT NULL,
  PRIMARY KEY (`NU_COUNTRY_ID`),
  UNIQUE KEY `UQ_BM_COUNTRY_ISO3166` (`TX_ISO3166_CODE`),
  UNIQUE KEY `UQ_BM_COUNTRY_ITU_T212` (`TX_ITU_T212_CODE`),
  KEY `FK_BM_CURRENCY_BM_COUNTRY` (`NU_CURRENCY_ID`),
  KEY `FK_BM_LANGUAGE_BM_COUNTRY` (`NU_LANGUAGE_ID`),
  CONSTRAINT `FK_BM_CURRENCY_BM_COUNTRY` FOREIGN KEY (`NU_CURRENCY_ID`) REFERENCES `BM_CURRENCY` (`NU_CURRENCY_ID`),
  CONSTRAINT `FK_BM_LANGUAGE_BM_COUNTRY` FOREIGN KEY (`NU_LANGUAGE_ID`) REFERENCES `BM_LANGUAGE` (`NU_LANGUAGE_ID`)
) ENGINE=INNODB DEFAULT CHARSET=LATIN1 ROW_FORMAT=COMPACT;

#
# STRUCTURE FOR TABLE "BM_METHODS_OF_PAYMENT"
#

DROP TABLE IF EXISTS `BM_METHODS_OF_PAYMENT`;
CREATE TABLE `BM_METHODS_OF_PAYMENT` (
  `NU_MOP_ID` BIGINT(10) NOT NULL,
  `TX_NAME` VARCHAR(20) CHARACTER SET LATIN1 COLLATE LATIN1_BIN NOT NULL,
  `TX_DESCRIPTION` VARCHAR(250) CHARACTER SET LATIN1 COLLATE LATIN1_BIN DEFAULT NULL,
  `TX_CODE` VARCHAR(20) CHARACTER SET LATIN1 COLLATE LATIN1_BIN DEFAULT NULL,
  PRIMARY KEY (`NU_MOP_ID`),
  UNIQUE KEY `UQ_MOP_NAME` (`TX_NAME`),
  UNIQUE KEY `UQ_MOP_CODE` (`TX_CODE`)
) ENGINE=INNODB DEFAULT CHARSET=LATIN1 ROW_FORMAT=COMPACT;

#
# STRUCTURE FOR TABLE "BM_CUSTOMER_TYPE"
#

DROP TABLE IF EXISTS `BM_CUSTOMER_TYPE`;
CREATE TABLE `BM_CUSTOMER_TYPE` (
  `NU_CUSTOMER_TYPE_ID` BIGINT(10) NOT NULL,
  `TX_NAME` VARCHAR(20) CHARACTER SET LATIN1 COLLATE LATIN1_BIN NOT NULL,
  `TX_DESCRIPTION` VARCHAR(250) CHARACTER SET LATIN1 COLLATE LATIN1_BIN DEFAULT NULL,
  `NU_MOP_ID` BIGINT(10) NOT NULL,
  PRIMARY KEY (`NU_CUSTOMER_TYPE_ID`),
  UNIQUE KEY `UQ_CUSTOMER_TYPE_NAME` (`TX_NAME`),
  KEY `FK_BM_METHOFPAY_BM_CUSTOM_TYPE` (`NU_MOP_ID`),
  CONSTRAINT `FK_BM_METHOFPAY_BM_CUSTOM_TYPE` FOREIGN KEY (`NU_MOP_ID`) REFERENCES `BM_METHODS_OF_PAYMENT` (`NU_MOP_ID`)
) ENGINE=INNODB DEFAULT CHARSET=LATIN1 ROW_FORMAT=COMPACT;

#
# STRUCTURE FOR TABLE "BM_OB"
#

DROP TABLE IF EXISTS `BM_OB`;
CREATE TABLE `BM_OB` (
  `NU_OB_ID` BIGINT(10) NOT NULL,
  `TX_NAME` VARCHAR(20) CHARACTER SET LATIN1 COLLATE LATIN1_BIN NOT NULL,
  `NU_COUNTRY_ID` BIGINT(10) NOT NULL,
  `TX_BRAND` VARCHAR(20) CHARACTER SET LATIN1 COLLATE LATIN1_BIN NOT NULL,
  PRIMARY KEY (`NU_OB_ID`),
  UNIQUE KEY `UQ_BM_OB_NAME` (`TX_NAME`),
  KEY `FK_BM_COUNTRY_BM_OB` (`NU_COUNTRY_ID`),
  CONSTRAINT `FK_BM_COUNTRY_BM_OB` FOREIGN KEY (`NU_COUNTRY_ID`) REFERENCES `BM_COUNTRY` (`NU_COUNTRY_ID`)
) ENGINE=INNODB DEFAULT CHARSET=LATIN1 ROW_FORMAT=COMPACT;

#
# STRUCTURE FOR TABLE "BM_OB_COUNTRY"
#

DROP TABLE IF EXISTS `BM_OB_COUNTRY`;
CREATE TABLE `BM_OB_COUNTRY` (
  `NU_OB_ID` BIGINT(10) NOT NULL,
  `NU_COUNTRY_ID` BIGINT(10) NOT NULL,
  `TC_PRICEPOINTS_YN` VARCHAR(20) CHARACTER SET LATIN1 COLLATE LATIN1_BIN DEFAULT NULL,
  `TX_MNC_ITU_T212` VARCHAR(20) CHARACTER SET LATIN1 COLLATE LATIN1_BIN DEFAULT NULL,
  PRIMARY KEY (`NU_OB_ID`,`NU_COUNTRY_ID`),
  KEY `FK_BM_COUNTRY_BM_OB_COUNTRY` (`NU_COUNTRY_ID`),
  KEY `INX_MNC_ITU_T212` (`TX_MNC_ITU_T212`),
  CONSTRAINT `FK_BM_COUNTRY_BM_OB_COUNTRY` FOREIGN KEY (`NU_COUNTRY_ID`) REFERENCES `BM_COUNTRY` (`NU_COUNTRY_ID`),
  CONSTRAINT `FK_BM_OB_BM_OB_COUNTRY` FOREIGN KEY (`NU_OB_ID`) REFERENCES `BM_OB` (`NU_OB_ID`)
) ENGINE=INNODB DEFAULT CHARSET=LATIN1 ROW_FORMAT=COMPACT;

#
# STRUCTURE FOR TABLE "BM_PAYMENTBROKER"
#

DROP TABLE IF EXISTS `BM_PAYMENTBROKER`;
CREATE TABLE `BM_PAYMENTBROKER` (
  `BM_PB_ID` BIGINT(10) NOT NULL,
  `TX_NAME` VARCHAR(20) CHARACTER SET LATIN1 COLLATE LATIN1_BIN DEFAULT NULL,
  PRIMARY KEY (`BM_PB_ID`),
  UNIQUE KEY `UQ_BM_PAYMENTBROKER_NAME` (`TX_NAME`)
) ENGINE=INNODB DEFAULT CHARSET=LATIN1 ROW_FORMAT=COMPACT;

#
# STRUCTURE FOR TABLE "BM_OB_MOP"
#

DROP TABLE IF EXISTS `BM_OB_MOP`;
CREATE TABLE `BM_OB_MOP` (
  `NU_OB_ID` BIGINT(10) NOT NULL,
  `NU_COUNTRY_ID` BIGINT(10) NOT NULL,
  `NU_MOP_ID` BIGINT(10) NOT NULL,
  `BM_PB_ID` BIGINT(10) DEFAULT NULL,
  `DT_START_DATE` DATETIME NOT NULL,
  PRIMARY KEY (`NU_MOP_ID`,`NU_COUNTRY_ID`,`NU_OB_ID`),
  KEY `FK_BM_OB_COUNTRY_BM_OB_MOP` (`NU_OB_ID`,`NU_COUNTRY_ID`),
  KEY `FK_BM_PAYMENTBROKER_BM_OB_MOP` (`BM_PB_ID`),
  CONSTRAINT `FK_BM_METHOFPAY_BM_OB_MOP` FOREIGN KEY (`NU_MOP_ID`) REFERENCES `BM_METHODS_OF_PAYMENT` (`NU_MOP_ID`),
  CONSTRAINT `FK_BM_OB_COUNTRY_BM_OB_MOP` FOREIGN KEY (`NU_OB_ID`, `NU_COUNTRY_ID`) REFERENCES `BM_OB_COUNTRY` (`NU_OB_ID`, `NU_COUNTRY_ID`),
  CONSTRAINT `FK_BM_PAYMENTBROKER_BM_OB_MOP` FOREIGN KEY (`BM_PB_ID`) REFERENCES `BM_PAYMENTBROKER` (`BM_PB_ID`)
) ENGINE=INNODB DEFAULT CHARSET=LATIN1 ROW_FORMAT=COMPACT;

#
# STRUCTURE FOR TABLE "BM_PB_MOP"
#

DROP TABLE IF EXISTS `BM_PB_MOP`;
CREATE TABLE `BM_PB_MOP` (
  `BM_PB_ID` BIGINT(10) NOT NULL,
  `NU_MOP_ID` BIGINT(10) NOT NULL,
  `TX_PAYMENTMETHOD_CODE` VARCHAR(20) CHARACTER SET LATIN1 COLLATE LATIN1_BIN DEFAULT NULL,
  PRIMARY KEY (`BM_PB_ID`,`NU_MOP_ID`),
  KEY `FK_BM_METHOFPAY_BM_PB_MOP` (`NU_MOP_ID`),
  CONSTRAINT `FK_BM_METHOFPAY_BM_PB_MOP` FOREIGN KEY (`NU_MOP_ID`) REFERENCES `BM_METHODS_OF_PAYMENT` (`NU_MOP_ID`),
  CONSTRAINT `FK_BM_PAYMENTBROKER_BM_PB_MOP` FOREIGN KEY (`BM_PB_ID`) REFERENCES `BM_PAYMENTBROKER` (`BM_PB_ID`)
) ENGINE=INNODB DEFAULT CHARSET=LATIN1 ROW_FORMAT=COMPACT;

#
# STRUCTURE FOR TABLE "BM_PRICE_POINT"
#

DROP TABLE IF EXISTS `BM_PRICE_POINT`;
CREATE TABLE `BM_PRICE_POINT` (
  `TX_PRICE_POINT_ID` VARCHAR(64) CHARACTER SET LATIN1 COLLATE LATIN1_BIN NOT NULL,
  `NU_PRICE` DECIMAL(20,5) NOT NULL,
  `DT_EDIT_DATE` DATETIME NOT NULL,
  `NU_OB_ID` BIGINT(10) NOT NULL,
  `NU_COUNTRY_ID` BIGINT(10) NOT NULL,
  `NU_CURRENCY_ID` BIGINT(10) NOT NULL,
  PRIMARY KEY (`TX_PRICE_POINT_ID`,`NU_OB_ID`,`NU_COUNTRY_ID`),
  KEY `FK_BM_OB_COUNTRY_BM_PRICEPOINT` (`NU_OB_ID`,`NU_COUNTRY_ID`),
  KEY `FK_CURRENCY_VS_PRICE_POINT` (`NU_CURRENCY_ID`),
  CONSTRAINT `FK_BM_OB_COUNTRY_BM_PRICEPOINT` FOREIGN KEY (`NU_OB_ID`, `NU_COUNTRY_ID`) REFERENCES `BM_OB_COUNTRY` (`NU_OB_ID`, `NU_COUNTRY_ID`),
  CONSTRAINT `FK_CURRENCY_VS_PRICE_POINT` FOREIGN KEY (`NU_CURRENCY_ID`) REFERENCES `BM_CURRENCY` (`NU_CURRENCY_ID`)
) ENGINE=INNODB DEFAULT CHARSET=LATIN1 ROW_FORMAT=COMPACT;

#
# STRUCTURE FOR TABLE "BM_SERVICE"
#

DROP TABLE IF EXISTS `BM_SERVICE`;
CREATE TABLE `BM_SERVICE` (
  `NU_SERVICE_ID` BIGINT(10) NOT NULL,
  `TX_NAME` VARCHAR(20) CHARACTER SET LATIN1 COLLATE LATIN1_BIN NOT NULL,
  `TX_DESCRIPTION` VARCHAR(250) CHARACTER SET LATIN1 COLLATE LATIN1_BIN DEFAULT NULL,
  `TC_THIRDPARTIES_YN` CHAR(1) CHARACTER SET LATIN1 COLLATE LATIN1_BIN NOT NULL,
  `DT_START_DATE` DATETIME NOT NULL,
  `TC_STATUS` CHAR(1) CHARACTER SET LATIN1 COLLATE LATIN1_BIN NOT NULL,
  `TC_API_TAXES_YN` CHAR(1) CHARACTER SET LATIN1 COLLATE LATIN1_BIN NOT NULL DEFAULT 'N',
  PRIMARY KEY (`NU_SERVICE_ID`),
  UNIQUE KEY `UQ_BM_SERVICE_NAME` (`TX_NAME`)
) ENGINE=INNODB DEFAULT CHARSET=LATIN1 ROW_FORMAT=COMPACT;

#
# STRUCTURE FOR TABLE "BM_SERVICE_DEPLOYMENT"
#

DROP TABLE IF EXISTS `BM_SERVICE_DEPLOYMENT`;
CREATE TABLE `BM_SERVICE_DEPLOYMENT` (
  `NU_DEPLOYMENT_ID` BIGINT(10) NOT NULL,
  `NU_SERVICE_ID` BIGINT(10) NOT NULL,
  `NU_OB_ID` BIGINT(10) NOT NULL,
  `NU_COUNTRY_ID` BIGINT(10) NOT NULL,
  `DT_DEPLOYMENT_DATE` DATETIME DEFAULT NULL,
  `TC_STATUS` CHAR(1) CHARACTER SET LATIN1 COLLATE LATIN1_BIN NOT NULL,
  PRIMARY KEY (`NU_DEPLOYMENT_ID`),
  UNIQUE KEY `UQ_SERVOBCOUNT_DEPLOYMENT` (`NU_SERVICE_ID`,`NU_OB_ID`,`NU_COUNTRY_ID`),
  KEY `FK_BM_OB_COUNT_BM_SERV_DEPLOY` (`NU_OB_ID`,`NU_COUNTRY_ID`),
  CONSTRAINT `FK_BM_OB_COUNT_BM_SERV_DEPLOY` FOREIGN KEY (`NU_OB_ID`, `NU_COUNTRY_ID`) REFERENCES `BM_OB_COUNTRY` (`NU_OB_ID`, `NU_COUNTRY_ID`),
  CONSTRAINT `FK_BM_SERVICE_BM_SERVICE_DEPLO` FOREIGN KEY (`NU_SERVICE_ID`) REFERENCES `BM_SERVICE` (`NU_SERVICE_ID`)
) ENGINE=INNODB DEFAULT CHARSET=LATIN1 ROW_FORMAT=COMPACT;

#
# STRUCTURE FOR TABLE "BM_SERVDEPLOY_MOP"
#

DROP TABLE IF EXISTS `BM_SERVDEPLOY_MOP`;
CREATE TABLE `BM_SERVDEPLOY_MOP` (
  `NU_SERVICE_MOP_ID` BIGINT(10) NOT NULL,
  `NU_MOP_ID` BIGINT(10) NOT NULL,
  `NU_CUSTOMER_TYPE_ID` BIGINT(10) NOT NULL,
  `NU_DEPLOYMENT_ID` BIGINT(10) NOT NULL,
  `TC_DEFAULT_YN` CHAR(1) CHARACTER SET LATIN1 COLLATE LATIN1_BIN NOT NULL,
  PRIMARY KEY (`NU_SERVICE_MOP_ID`),
  KEY `FK_BM_CUSTO_TYPE_BM_SERDEP_MOP` (`NU_CUSTOMER_TYPE_ID`),
  KEY `FK_BM_METHOFPAY_BM_SERVDEP_MOP` (`NU_MOP_ID`),
  KEY `FK_BM_SERV_DEPL_BM_SERVDEP_MOP` (`NU_DEPLOYMENT_ID`),
  CONSTRAINT `FK_BM_CUSTO_TYPE_BM_SERDEP_MOP` FOREIGN KEY (`NU_CUSTOMER_TYPE_ID`) REFERENCES `BM_CUSTOMER_TYPE` (`NU_CUSTOMER_TYPE_ID`),
  CONSTRAINT `FK_BM_METHOFPAY_BM_SERVDEP_MOP` FOREIGN KEY (`NU_MOP_ID`) REFERENCES `BM_METHODS_OF_PAYMENT` (`NU_MOP_ID`),
  CONSTRAINT `FK_BM_SERV_DEPL_BM_SERVDEP_MOP` FOREIGN KEY (`NU_DEPLOYMENT_ID`) REFERENCES `BM_SERVICE_DEPLOYMENT` (`NU_DEPLOYMENT_ID`)
) ENGINE=INNODB DEFAULT CHARSET=LATIN1 ROW_FORMAT=COMPACT;

#
# STRUCTURE FOR TABLE "BM_SERVICE_PRODUCT_TYPE"
#

DROP TABLE IF EXISTS `BM_SERVICE_PRODUCT_TYPE`;
CREATE TABLE `BM_SERVICE_PRODUCT_TYPE` (
  `NU_SERVICE_PRODUCT_TYPE_ID` BIGINT(10) NOT NULL,
  `TX_NAME` VARCHAR(20) CHARACTER SET LATIN1 COLLATE LATIN1_BIN NOT NULL,
  `TX_DESCRIPTION` VARCHAR(250) CHARACTER SET LATIN1 COLLATE LATIN1_BIN DEFAULT NULL,
  `NU_SERVICE_ID` BIGINT(10) NOT NULL,
  `TC_IS_DEFAULT_YN` CHAR(1) CHARACTER SET LATIN1 COLLATE LATIN1_BIN DEFAULT 'N',
  PRIMARY KEY (`NU_SERVICE_ID`,`NU_SERVICE_PRODUCT_TYPE_ID`),
  UNIQUE KEY `UQ_SERVICE_PRODUCT_TYPE_NAME` (`NU_SERVICE_ID`,`TX_NAME`),
  CONSTRAINT `FK_BM_SERVICE_BM_SERV_PROD_TYP` FOREIGN KEY (`NU_SERVICE_ID`) REFERENCES `BM_SERVICE` (`NU_SERVICE_ID`)
) ENGINE=INNODB DEFAULT CHARSET=LATIN1 ROW_FORMAT=COMPACT;

#
# STRUCTURE FOR TABLE "BM_PRODUCT"
#

DROP TABLE IF EXISTS `BM_PRODUCT`;
CREATE TABLE `BM_PRODUCT` (
  `NU_PRODUCT_ID` BIGINT(10) NOT NULL,
  `TX_NAME` VARCHAR(40) CHARACTER SET LATIN1 COLLATE LATIN1_BIN NOT NULL,
  `TX_PRODUCT_DESCRIPTION` VARCHAR(250) CHARACTER SET LATIN1 COLLATE LATIN1_BIN DEFAULT NULL,
  `NU_SERVICE_ID` BIGINT(10) NOT NULL,
  `TC_IS_SERVICE_PRODUCT_YN` CHAR(1) CHARACTER SET LATIN1 COLLATE LATIN1_BIN NOT NULL DEFAULT 'N',
  `NU_SERVICE_PRODUCT_TYPE_ID` BIGINT(10) DEFAULT NULL,
  PRIMARY KEY (`NU_PRODUCT_ID`),
  UNIQUE KEY `UQ_PRODUCT_ID_AND_SERVICE` (`NU_SERVICE_ID`,`TX_NAME`),
  KEY `FK_BM_SE_PR_TYPE_BM_PRODUCT` (`NU_SERVICE_ID`,`NU_SERVICE_PRODUCT_TYPE_ID`),
  CONSTRAINT `FK_BM_SERVICE_BM_PRODUCT` FOREIGN KEY (`NU_SERVICE_ID`) REFERENCES `BM_SERVICE` (`NU_SERVICE_ID`),
  CONSTRAINT `FK_BM_SE_PR_TYPE_BM_PRODUCT` FOREIGN KEY (`NU_SERVICE_ID`, `NU_SERVICE_PRODUCT_TYPE_ID`) REFERENCES `BM_SERVICE_PRODUCT_TYPE` (`NU_SERVICE_ID`, `NU_SERVICE_PRODUCT_TYPE_ID`)
) ENGINE=INNODB DEFAULT CHARSET=LATIN1 ROW_FORMAT=COMPACT;

#
# STRUCTURE FOR TABLE "BM_PRODUCT_VS_OB"
#

DROP TABLE IF EXISTS `BM_PRODUCT_VS_OB`;
CREATE TABLE `BM_PRODUCT_VS_OB` (
  `NU_PRODUCT_ID` BIGINT(10) NOT NULL,
  `NU_DEPLOYMENT_ID` BIGINT(10) NOT NULL,
  `NU_PRICE` DECIMAL(10,4) DEFAULT NULL,
  PRIMARY KEY (`NU_PRODUCT_ID`,`NU_DEPLOYMENT_ID`),
  KEY `FK_BM_SERV_DEPL_BM_PROD_VS_OB` (`NU_DEPLOYMENT_ID`),
  CONSTRAINT `FK_BM_PRODUCT_BM_PRODUCT_VS_OB` FOREIGN KEY (`NU_PRODUCT_ID`) REFERENCES `BM_PRODUCT` (`NU_PRODUCT_ID`),
  CONSTRAINT `FK_BM_SERV_DEPL_BM_PROD_VS_OB` FOREIGN KEY (`NU_DEPLOYMENT_ID`) REFERENCES `BM_SERVICE_DEPLOYMENT` (`NU_DEPLOYMENT_ID`)
) ENGINE=INNODB DEFAULT CHARSET=LATIN1 ROW_FORMAT=COMPACT;

#
# STRUCTURE FOR TABLE "DBE_AGGREGATOR"
#

DROP TABLE IF EXISTS `DBE_AGGREGATOR`;
CREATE TABLE `DBE_AGGREGATOR` (
  `TX_EMAIL` VARCHAR(255) CHARACTER SET LATIN1 COLLATE LATIN1_BIN NOT NULL DEFAULT '',
  `TX_NAME` VARCHAR(100) CHARACTER SET LATIN1 COLLATE LATIN1_BIN NOT NULL DEFAULT '',
  PRIMARY KEY (`TX_EMAIL`)
) ENGINE=INNODB DEFAULT CHARSET=LATIN1;

#
# STRUCTURE FOR TABLE "DBE_APPPROVIDER"
#

DROP TABLE IF EXISTS `DBE_APPPROVIDER`;
CREATE TABLE `DBE_APPPROVIDER` (
  `TX_APPPROVIDER_ID` VARCHAR(50) CHARACTER SET LATIN1 COLLATE LATIN1_BIN NOT NULL,
  `TX_NAME` VARCHAR(256) CHARACTER SET LATIN1 COLLATE LATIN1_BIN NOT NULL,
  PRIMARY KEY (`TX_APPPROVIDER_ID`)
) ENGINE=INNODB DEFAULT CHARSET=LATIN1 ROW_FORMAT=COMPACT;

#
# STRUCTURE FOR TABLE "DBE_AGGREGATOR_APPPROVIDER"
#

DROP TABLE IF EXISTS `DBE_AGGREGATOR_APPPROVIDER`;
CREATE TABLE `DBE_AGGREGATOR_APPPROVIDER` (
  `TX_EMAIL` VARCHAR(255) CHARACTER SET LATIN1 COLLATE LATIN1_BIN NOT NULL DEFAULT '',
  `TX_APPPROVIDER_ID` VARCHAR(50) CHARACTER SET LATIN1 COLLATE LATIN1_BIN NOT NULL DEFAULT '',
  KEY `FK_DBE_AGG_PROV_DBE_AGG` (`TX_EMAIL`),
  KEY `FK_DBE_AGG_PROV_DBE_APP` (`TX_APPPROVIDER_ID`),
  CONSTRAINT `FK_DBE_AGG_PROV_DBE_AGG` FOREIGN KEY (`TX_EMAIL`) REFERENCES `DBE_AGGREGATOR` (`TX_EMAIL`),
  CONSTRAINT `FK_DBE_AGG_PROV_DBE_APP` FOREIGN KEY (`TX_APPPROVIDER_ID`) REFERENCES `DBE_APPPROVIDER` (`TX_APPPROVIDER_ID`)
) ENGINE=INNODB DEFAULT CHARSET=LATIN1;

#
# STRUCTURE FOR TABLE "DBE_APPPROVIDER_APPLICATION"
#

DROP TABLE IF EXISTS `DBE_APPPROVIDER_APPLICATION`;
CREATE TABLE `DBE_APPPROVIDER_APPLICATION` (
  `TX_APPLICATION_ID` VARCHAR(50) CHARACTER SET LATIN1 COLLATE LATIN1_BIN NOT NULL,
  `TX_APPPROVIDER_ID` VARCHAR(50) CHARACTER SET LATIN1 COLLATE LATIN1_BIN NOT NULL,
  PRIMARY KEY (`TX_APPPROVIDER_ID`,`TX_APPLICATION_ID`),
  CONSTRAINT `FK_APPPROV_VS_APPPROV_APPLICAT` FOREIGN KEY (`TX_APPPROVIDER_ID`) REFERENCES `DBE_APPPROVIDER` (`TX_APPPROVIDER_ID`)
) ENGINE=INNODB DEFAULT CHARSET=LATIN1 ROW_FORMAT=COMPACT;

#
# STRUCTURE FOR TABLE "DBE_EXPEND_CONTROL"
#

DROP TABLE IF EXISTS `DBE_EXPEND_CONTROL`;
CREATE TABLE `DBE_EXPEND_CONTROL` (
  `NU_SERVICE_ID` BIGINT(10) NOT NULL,
  `NU_CURRENCY_ID` BIGINT(10) NOT NULL,
  `TX_APPPROVIDER_ID` VARCHAR(40) CHARACTER SET LATIN1 COLLATE LATIN1_BIN NOT NULL,
  `NU_OB_ID` BIGINT(10) NOT NULL,
  `NU_COUNTRY_ID` BIGINT(10) NOT NULL,
  `FT_EXPENSED_AMOUNT` DECIMAL(12,4) DEFAULT NULL,
  `DT_NEXT_PERIOD_START` DATETIME DEFAULT NULL,
  `TX_NOTIFICATIONS` VARCHAR(100) CHARACTER SET LATIN1 COLLATE LATIN1_BIN DEFAULT NULL,
  `TX_EL_TYPE` VARCHAR(20) CHARACTER SET LATIN1 COLLATE LATIN1_BIN NOT NULL,
  `TX_END_USER_ID` VARCHAR(100) CHARACTER SET LATIN1 COLLATE LATIN1_BIN NOT NULL,
  PRIMARY KEY (`NU_SERVICE_ID`,`NU_CURRENCY_ID`,`NU_OB_ID`,`NU_COUNTRY_ID`,`TX_EL_TYPE`,`TX_END_USER_ID`,`TX_APPPROVIDER_ID`),
  KEY `FK_DBE_EXPEND_CONTROL_BM_CURRENCY` (`NU_CURRENCY_ID`),
  KEY `FK_DBE_EXPEND_CONTROL_BM_OB_COUNTRY` (`NU_OB_ID`,`NU_COUNTRY_ID`),
  KEY `FK_DBE_EXPEND_CONTROL_DBE_APPPROVIDER` (`TX_APPPROVIDER_ID`),
  CONSTRAINT `FK_DBE_EXPEND_CONTROL_BM_CURRENCY` FOREIGN KEY (`NU_CURRENCY_ID`) REFERENCES `BM_CURRENCY` (`NU_CURRENCY_ID`),
  CONSTRAINT `FK_DBE_EXPEND_CONTROL_BM_OB_COUNTRY` FOREIGN KEY (`NU_OB_ID`, `NU_COUNTRY_ID`) REFERENCES `BM_OB_COUNTRY` (`NU_OB_ID`, `NU_COUNTRY_ID`),
  CONSTRAINT `FK_DBE_EXPEND_CONTROL_BM_SERVICE` FOREIGN KEY (`NU_SERVICE_ID`) REFERENCES `BM_SERVICE` (`NU_SERVICE_ID`),
  CONSTRAINT `FK_DBE_EXPEND_CONTROL_DBE_APPPROVIDER` FOREIGN KEY (`TX_APPPROVIDER_ID`) REFERENCES `DBE_APPPROVIDER` (`TX_APPPROVIDER_ID`)
) ENGINE=INNODB DEFAULT CHARSET=LATIN1 ROW_FORMAT=COMPACT;

#
# STRUCTURE FOR TABLE "DBE_EXPEND_LIMIT"
#

DROP TABLE IF EXISTS `DBE_EXPEND_LIMIT`;
CREATE TABLE `DBE_EXPEND_LIMIT` (
  `TX_EL_TYPE` VARCHAR(20) CHARACTER SET LATIN1 COLLATE LATIN1_BIN NOT NULL,
  `FT_MAX_AMOUNT` DECIMAL(12,4) DEFAULT NULL,
  `TX_NOTIF_AMOUNTS` VARCHAR(100) CHARACTER SET LATIN1 COLLATE LATIN1_BIN DEFAULT NULL,
  `TX_END_USER_ID` VARCHAR(100) CHARACTER SET LATIN1 COLLATE LATIN1_BIN NOT NULL,
  `TX_APPPROVIDER_ID` VARCHAR(40) CHARACTER SET LATIN1 COLLATE LATIN1_BIN NOT NULL,
  `NU_OB_ID` BIGINT(10) NOT NULL,
  `NU_COUNTRY_ID` BIGINT(10) NOT NULL,
  `NU_SERVICE_ID` BIGINT(10) NOT NULL,
  `NU_CURRENCY_ID` BIGINT(10) NOT NULL,
  PRIMARY KEY (`NU_OB_ID`,`NU_CURRENCY_ID`,`TX_EL_TYPE`,`TX_END_USER_ID`,`NU_COUNTRY_ID`,`NU_SERVICE_ID`,`TX_APPPROVIDER_ID`),
  KEY `FK_DBE_EXPEND_LIMIT_BM_CURRENCY` (`NU_CURRENCY_ID`),
  KEY `FK_DBE_EXPEND_LIMIT_BM_OB_COUNTRY` (`NU_OB_ID`,`NU_COUNTRY_ID`),
  KEY `FK_DBE_EXPEND_LIMIT_BM_SERVICE` (`NU_SERVICE_ID`),
  KEY `FK_DBE_EXPEND_LIMIT_DBE_APPPROVIDER` (`TX_APPPROVIDER_ID`),
  CONSTRAINT `FK_DBE_EXPEND_LIMIT_BM_CURRENCY` FOREIGN KEY (`NU_CURRENCY_ID`) REFERENCES `BM_CURRENCY` (`NU_CURRENCY_ID`),
  CONSTRAINT `FK_DBE_EXPEND_LIMIT_BM_OB_COUNTRY` FOREIGN KEY (`NU_OB_ID`, `NU_COUNTRY_ID`) REFERENCES `BM_OB_COUNTRY` (`NU_OB_ID`, `NU_COUNTRY_ID`),
  CONSTRAINT `FK_DBE_EXPEND_LIMIT_BM_SERVICE` FOREIGN KEY (`NU_SERVICE_ID`) REFERENCES `BM_SERVICE` (`NU_SERVICE_ID`),
  CONSTRAINT `FK_DBE_EXPEND_LIMIT_DBE_APPPROVIDER` FOREIGN KEY (`TX_APPPROVIDER_ID`) REFERENCES `DBE_APPPROVIDER` (`TX_APPPROVIDER_ID`)
) ENGINE=INNODB DEFAULT CHARSET=LATIN1 ROW_FORMAT=COMPACT;

#
# STRUCTURE FOR TABLE "DBE_SYSTEM_PROPERTIES"
#

DROP TABLE IF EXISTS `DBE_SYSTEM_PROPERTIES`;
CREATE TABLE `DBE_SYSTEM_PROPERTIES` (
  `TX_PARAM_DATA_TYPE` VARCHAR(50) CHARACTER SET LATIN1 COLLATE LATIN1_BIN DEFAULT NULL,
  `TX_PARAM_NAME` VARCHAR(100) CHARACTER SET LATIN1 COLLATE LATIN1_BIN NOT NULL,
  `TX_PARAM_DESCRIPTION` VARCHAR(250) CHARACTER SET LATIN1 COLLATE LATIN1_BIN DEFAULT NULL,
  `TX_PARAM_VALUE` VARCHAR(500) CHARACTER SET LATIN1 COLLATE LATIN1_BIN DEFAULT NULL,
  `TX_PARAM_CLASS` VARCHAR(50) CHARACTER SET LATIN1 COLLATE LATIN1_BIN NOT NULL,
  PRIMARY KEY (`TX_PARAM_NAME`)
) ENGINE=INNODB DEFAULT CHARSET=LATIN1 ROW_FORMAT=COMPACT;

#
# STRUCTURE FOR TABLE "DBE_TRANSACTION"
#

DROP TABLE IF EXISTS `DBE_TRANSACTION`;
CREATE TABLE `DBE_TRANSACTION` (
  `TX_TRANSACTION_ID` VARCHAR(40) CHARACTER SET LATIN1 COLLATE LATIN1_BIN NOT NULL,
  `TS_REQUEST` DATETIME NOT NULL,
  `TS_RESPONSE` DATETIME DEFAULT NULL,
  `TX_END_USER_ID` VARCHAR(100) CHARACTER SET LATIN1 COLLATE LATIN1_BIN NOT NULL,
  `TC_TRANSACTION_TYPE` CHAR(1) CHARACTER SET LATIN1 COLLATE LATIN1_BIN NOT NULL,
  `TX_GLOBAL_USER_ID` VARCHAR(40) CHARACTER SET LATIN1 COLLATE LATIN1_BIN DEFAULT NULL,
  `TC_TRANSACTION_STATUS` CHAR(1) CHARACTER SET LATIN1 COLLATE LATIN1_BIN NOT NULL,
  `TX_ERR_CODE` VARCHAR(10) CHARACTER SET LATIN1 COLLATE LATIN1_BIN DEFAULT NULL,
  `TX_ERR_MSG` VARCHAR(250) CHARACTER SET LATIN1 COLLATE LATIN1_BIN DEFAULT NULL,
  `TX_REFERENCE_CODE` VARCHAR(40) CHARACTER SET LATIN1 COLLATE LATIN1_BIN NOT NULL,
  `TX_ORG_TRANSACTION_ID` VARCHAR(40) CHARACTER SET LATIN1 COLLATE LATIN1_BIN DEFAULT NULL,
  `TX_CALLBACK_URL` VARCHAR(300) CHARACTER SET LATIN1 COLLATE LATIN1_BIN DEFAULT NULL,
  `FT_CHARGED_TOTAL_AMOUNT` DECIMAL(9,4) DEFAULT NULL,
  `FT_REQUEST_AMOUNT` DECIMAL(9,4) DEFAULT NULL,
  `TX_REQUEST_CODE` VARCHAR(64) CHARACTER SET LATIN1 COLLATE LATIN1_BIN DEFAULT NULL,
  `NU_CURRENCY_ID` BIGINT(10) DEFAULT NULL,
  `FT_REQUEST_TAX_AMOUNT` DECIMAL(9,4) DEFAULT NULL,
  `NU_SERVICE_ID` BIGINT(10) NOT NULL,
  `NU_PRODUCT_ID` BIGINT(10) DEFAULT NULL,
  `TS_CLIENT_DATE` DATETIME DEFAULT NULL,
  `TX_OP_ATTRIBUTES` VARCHAR(1000) CHARACTER SET LATIN1 COLLATE LATIN1_BIN DEFAULT NULL,
  `TX_PB_CORRELATION_ID` VARCHAR(100) CHARACTER SET LATIN1 COLLATE LATIN1_BIN DEFAULT NULL,
  `TX_PARTITION` VARCHAR(2) CHARACTER SET LATIN1 COLLATE LATIN1_BIN NOT NULL,
  `TX_ORG_PB_CORRELATION_ID` VARCHAR(100) CHARACTER SET LATIN1 COLLATE LATIN1_BIN DEFAULT NULL,
  `TX_REQUEST_AMOUNT_DESC` VARCHAR(250) CHARACTER SET LATIN1 COLLATE LATIN1_BIN DEFAULT NULL,
  `TX_OPER_SERV_DESC` VARCHAR(250) CHARACTER SET LATIN1 COLLATE LATIN1_BIN DEFAULT NULL,
  `TX_TAXES_APPLIED` VARCHAR(250) CHARACTER SET LATIN1 COLLATE LATIN1_BIN DEFAULT NULL,
  `NU_INTERNAL_OB_ID` BIGINT(10) NOT NULL,
  `TX_PB_SPEC_DATA` VARCHAR(250) CHARACTER SET LATIN1 COLLATE LATIN1_BIN DEFAULT NULL,
  `NU_INTERNAL_COUNTRY_ID` BIGINT(10) NOT NULL,
  `NU_INTERNAL_MOP_ID` BIGINT(10) NOT NULL,
  `BM_PB_ID` BIGINT(10) DEFAULT NULL,
  `TX_TRANS_STATUS_DESC` VARCHAR(250) CHARACTER SET LATIN1 COLLATE LATIN1_BIN DEFAULT NULL,
  `NU_REQUEST_MOP_ID` BIGINT(10) DEFAULT NULL,
  `FT_INTERNAL_TOTAL_AMOUNT` DECIMAL(9,4) DEFAULT NULL,
  `FT_CHARGED_TAX_AMOUNT` DECIMAL(9,4) DEFAULT NULL,
  `FT_INTERNAL_TAX_AMOUNT` DECIMAL(9,4) DEFAULT NULL,
  `TX_PB_RESULT_CODE` VARCHAR(40) CHARACTER SET LATIN1 COLLATE LATIN1_BIN DEFAULT NULL,
  `TX_PB_RESULT_CODE_DESC` VARCHAR(256) CHARACTER SET LATIN1 COLLATE LATIN1_BIN DEFAULT NULL,
  `TX_MASKED_ACCOUNT_NUM` VARCHAR(30) CHARACTER SET LATIN1 COLLATE LATIN1_BIN DEFAULT NULL,
  `FT_REQUEST_TOTAL_AMOUNT` DECIMAL(8,4) DEFAULT NULL,
  `TX_CHANNEL` VARCHAR(20) CHARACTER SET LATIN1 COLLATE LATIN1_BIN DEFAULT NULL,
  `TX_APPLICATION_ID` VARCHAR(40) CHARACTER SET LATIN1 COLLATE LATIN1_BIN NOT NULL,
  `TX_PRODUCT_CLASS` VARCHAR(40) CHARACTER SET LATIN1 COLLATE LATIN1_BIN DEFAULT NULL,
  `TX_MERCHANT_ID` VARCHAR(40) CHARACTER SET LATIN1 COLLATE LATIN1_BIN DEFAULT NULL,
  `TX_OPERATION_NATURE` VARCHAR(40) CHARACTER SET LATIN1 COLLATE LATIN1_BIN DEFAULT NULL,
  `TC_IS_REFUNDED_YN` CHAR(1) CHARACTER SET LATIN1 COLLATE LATIN1_BIN NOT NULL DEFAULT 'N',
  `TC_IS_CAPTURED_YN` CHAR(1) CHARACTER SET LATIN1 COLLATE LATIN1_BIN NOT NULL DEFAULT 'N',
  `NU_CLIENT_COUNTRY_ID` BIGINT(10) DEFAULT NULL,
  `NU_CLIENT_OB_ID` BIGINT(10) DEFAULT NULL,
  `TX_SUBTYPE_MOP` VARCHAR(20) CHARACTER SET LATIN1 COLLATE LATIN1_BIN DEFAULT NULL,
  `TX_CLIENT_ZIP_CODE` VARCHAR(20) CHARACTER SET LATIN1 COLLATE LATIN1_BIN DEFAULT NULL,
  `TS_STATUS_DATE` DATETIME NOT NULL,
  `TX_APP_PROVIDER` VARCHAR(20) CHARACTER SET LATIN1 COLLATE LATIN1_BIN DEFAULT NULL,
  `TX_PB_URL_REDIRECTION` VARCHAR(512) CHARACTER SET LATIN1 COLLATE LATIN1_BIN DEFAULT NULL,
  `TX_REFUND_REASON` VARCHAR(40) CHARACTER SET LATIN1 COLLATE LATIN1_BIN DEFAULT NULL,
  `TX_REDIRECT_URL` VARCHAR(512) CHARACTER SET LATIN1 COLLATE LATIN1_BIN DEFAULT NULL,
  `FT_INTERNAL_AMOUNT` DECIMAL(9,4) DEFAULT NULL,
  `FT_CHARGED_AMOUNT` DECIMAL(9,4) DEFAULT NULL,
  PRIMARY KEY (`TX_TRANSACTION_ID`),
  UNIQUE KEY `UQ_REFERENCE_X_SERV` (`TX_REFERENCE_CODE`,`NU_SERVICE_ID`,`TX_APPLICATION_ID`),
  KEY `FK_BM_CURRENCY_DBE_TRANSACTION` (`NU_CURRENCY_ID`),
  KEY `FK_BM_MOP_DBE_TRANSACTION` (`NU_REQUEST_MOP_ID`),
  KEY `FK_BM_OB_COUNTRY_DBE_TRANSACT` (`NU_CLIENT_OB_ID`,`NU_CLIENT_COUNTRY_ID`),
  KEY `FK_BM_OB_MOP_DBE_TRANSACTION` (`NU_INTERNAL_OB_ID`,`NU_INTERNAL_COUNTRY_ID`,`NU_INTERNAL_MOP_ID`),
  KEY `FK_BM_PBROKER_DBE_TRANSACTION` (`BM_PB_ID`),
  KEY `FK_BM_PRODUCT_DBE_TRANSACTION` (`NU_PRODUCT_ID`),
  KEY `FK_BM_SERVICE_DBE_TRANSACTION` (`NU_SERVICE_ID`),
  CONSTRAINT `FK_BM_CURRENCY_DBE_TRANSACTION` FOREIGN KEY (`NU_CURRENCY_ID`) REFERENCES `BM_CURRENCY` (`NU_CURRENCY_ID`),
  CONSTRAINT `FK_BM_MOP_DBE_TRANSACTION` FOREIGN KEY (`NU_REQUEST_MOP_ID`) REFERENCES `BM_METHODS_OF_PAYMENT` (`NU_MOP_ID`),
  CONSTRAINT `FK_BM_OB_COUNTRY_DBE_TRANSACT` FOREIGN KEY (`NU_CLIENT_OB_ID`, `NU_CLIENT_COUNTRY_ID`) REFERENCES `BM_OB_COUNTRY` (`NU_OB_ID`, `NU_COUNTRY_ID`),
  CONSTRAINT `FK_BM_OB_MOP_DBE_TRANSACTION` FOREIGN KEY (`NU_INTERNAL_OB_ID`, `NU_INTERNAL_COUNTRY_ID`, `NU_INTERNAL_MOP_ID`) REFERENCES `BM_OB_MOP` (`NU_OB_ID`, `NU_COUNTRY_ID`, `NU_MOP_ID`),
  CONSTRAINT `FK_BM_PBROKER_DBE_TRANSACTION` FOREIGN KEY (`BM_PB_ID`) REFERENCES `BM_PAYMENTBROKER` (`BM_PB_ID`),
  CONSTRAINT `FK_BM_PRODUCT_DBE_TRANSACTION` FOREIGN KEY (`NU_PRODUCT_ID`) REFERENCES `BM_PRODUCT` (`NU_PRODUCT_ID`),
  CONSTRAINT `FK_BM_SERVICE_DBE_TRANSACTION` FOREIGN KEY (`NU_SERVICE_ID`) REFERENCES `BM_SERVICE` (`NU_SERVICE_ID`)
) ENGINE=INNODB DEFAULT CHARSET=LATIN1 ROW_FORMAT=COMPACT;

#
# STRUCTURE FOR TABLE "SET_REVENUE_SHARE_CONF"
#

DROP TABLE IF EXISTS `SET_REVENUE_SHARE_CONF`;
CREATE TABLE `SET_REVENUE_SHARE_CONF` (
  `TX_APPPROVIDER_ID` VARCHAR(50) CHARACTER SET LATIN1 COLLATE LATIN1_BIN NOT NULL,
  `NU_OB_ID` BIGINT(10) NOT NULL,
  `NU_COUNTRY_ID` BIGINT(10) NOT NULL,
  `NU_PERC_REVENUE_SHARE` INT(5) NOT NULL DEFAULT '0',
  `TX_PRODUCT_CLASS` VARCHAR(40) NOT NULL DEFAULT '',
  PRIMARY KEY (`TX_APPPROVIDER_ID`,`NU_OB_ID`,`TX_PRODUCT_CLASS`,`NU_COUNTRY_ID`),
  KEY `FK_OB_COUN_TO_REVENEU_SHARE_C` (`NU_OB_ID`,`NU_COUNTRY_ID`),
  CONSTRAINT `FK_APPPROV_TO_REVENEU_SHARE_C` FOREIGN KEY (`TX_APPPROVIDER_ID`) REFERENCES `DBE_APPPROVIDER` (`TX_APPPROVIDER_ID`),
  CONSTRAINT `FK_OB_COUN_TO_REVENEU_SHARE_C` FOREIGN KEY (`NU_OB_ID`, `NU_COUNTRY_ID`) REFERENCES `BM_OB_COUNTRY` (`NU_OB_ID`, `NU_COUNTRY_ID`)
) ENGINE=INNODB DEFAULT CHARSET=LATIN1 ROW_FORMAT=COMPACT;