/**
 * Revenue Settlement and Sharing System GE
 * Copyright (C) 2011-2014,  Javier Lucio - lucio@tid.es
 * Telefonica Investigacion y Desarrollo, S.A.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

package es.upm.fiware.rss.model;

// Generated 10-feb-2012 11:04:29 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Cacheable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;

/**
 * BmCustomerType generated by hbm2java.
 */
@Entity
@Table(name = "bm_customer_type")
@Cacheable
@Cache(usage = CacheConcurrencyStrategy.READ_ONLY)
public class BmCustomerType implements java.io.Serializable {

    private long nuCustomerTypeId;
    private BmMethodsOfPayment bmMethodsOfPayment;
    private String txName;
    private String txDescription;
    private Set<BmServdeployMop> bmServdeployMops = new HashSet<BmServdeployMop>(0);

    /**
     * Constructor.
     */
    public BmCustomerType() {
    }

    /**
     * Constructor.
     * 
     * @param nuCustomerTypeId
     * @param bmMethodsOfPayment
     * @param txName
     */
    public BmCustomerType(long nuCustomerTypeId, BmMethodsOfPayment bmMethodsOfPayment, String txName) {
        this.nuCustomerTypeId = nuCustomerTypeId;
        this.bmMethodsOfPayment = bmMethodsOfPayment;
        this.txName = txName;
    }

    /**
     * Constructor.
     * 
     * @param nuCustomerTypeId
     * @param bmMethodsOfPayment
     * @param txName
     * @param txDescription
     * @param bmServdeployMops
     */
    public BmCustomerType(long nuCustomerTypeId, BmMethodsOfPayment bmMethodsOfPayment, String txName,
        String txDescription, Set<BmServdeployMop> bmServdeployMops) {
        this.nuCustomerTypeId = nuCustomerTypeId;
        this.bmMethodsOfPayment = bmMethodsOfPayment;
        this.txName = txName;
        this.txDescription = txDescription;
        this.bmServdeployMops = bmServdeployMops;
    }

    @Id
    @Column(name = "NU_CUSTOMER_TYPE_ID", unique = true, nullable = false, precision = 10, scale = 0)
    public long getNuCustomerTypeId() {
        return this.nuCustomerTypeId;
    }

    public void setNuCustomerTypeId(long nuCustomerTypeId) {
        this.nuCustomerTypeId = nuCustomerTypeId;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "NU_MOP_ID", nullable = false)
    public BmMethodsOfPayment getBmMethodsOfPayment() {
        return this.bmMethodsOfPayment;
    }

    public void setBmMethodsOfPayment(BmMethodsOfPayment bmMethodsOfPayment) {
        this.bmMethodsOfPayment = bmMethodsOfPayment;
    }

    @Column(name = "TX_NAME", nullable = false, length = 20)
    public String getTxName() {
        return this.txName;
    }

    public void setTxName(String txName) {
        this.txName = txName;
    }

    @Column(name = "TX_DESCRIPTION", length = 250)
    public String getTxDescription() {
        return this.txDescription;
    }

    public void setTxDescription(String txDescription) {
        this.txDescription = txDescription;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "bmCustomerType")
    public Set<BmServdeployMop> getBmServdeployMops() {
        return this.bmServdeployMops;
    }

    public void setBmServdeployMops(Set<BmServdeployMop> bmServdeployMops) {
        this.bmServdeployMops = bmServdeployMops;
    }

}
