/**
 * Revenue Settlement and Sharing System GE
 * Copyright (C) 2011-2014,  Javier Lucio - lucio@tid.es
 * Telefonica Investigacion y Desarrollo, S.A.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

package es.upm.fiware.rss.model;

// Generated 27-oct-2012 18:44:08 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * DbeServiceParams generated by hbm2java.
 */
@Entity
@Table(name = "dbe_system_properties")
public class DbeSystemProperties implements java.io.Serializable {

    private static final long serialVersionUID = 1L;
    private String txParamName;
    private String txParamDataType;
    private String txParamDescription;
    private String txParamValue;
    private String txParamClass;

    /**
     * 
     */
    public DbeSystemProperties() {
    }

    /**
     * @param txParamName
     * @param txParamValue
     * @param txParamClass
     */
    public DbeSystemProperties(String txParamName, String txParamValue, String txParamClass) {
        this.txParamName = txParamName;
        this.txParamClass = txParamClass;
        this.txParamValue = txParamValue;
    }

    @Id
    @Column(name = "TX_PARAM_NAME", length = 100)
    public String getTxParamName() {
        return txParamName;
    }

    public void setTxParamName(String txParamName) {
        this.txParamName = txParamName;
    }

    @Column(name = "TX_PARAM_CLASS", length = 50)
    public String getTxParamClass() {
        return txParamClass;
    }

    public void setTxParamClass(String txParamClass) {
        this.txParamClass = txParamClass;
    }

    @Column(name = "TX_PARAM_DATA_TYPE", length = 50)
    public String getTxParamDataType() {
        return this.txParamDataType;
    }

    public void setTxParamDataType(String txParamDataType) {
        this.txParamDataType = txParamDataType;
    }

    @Column(name = "TX_PARAM_DESCRIPTION", length = 250)
    public String getTxParamDescription() {
        return this.txParamDescription;
    }

    public void setTxParamDescription(String txParamDescription) {
        this.txParamDescription = txParamDescription;
    }

    @Column(name = "TX_PARAM_VALUE", length = 500)
    public String getTxParamValue() {
        return this.txParamValue;
    }

    public void setTxParamValue(String txParamValue) {
        this.txParamValue = txParamValue;
    }

}
